### ISSUE TITLE
Fix the overlapping of elements in the official website.

### ISSUE THREAD

**Issue by hilbert-yaa** [panda3d/www.panda3d.org#12]
## Description

Hi, I'm new to panda3d, when opening the official gallery website referred in readme file, I notice the website layout has some problem such that the download button and sdk version is mostly covered by the following box as shown in the picture below:
![image](https://user-images.githubusercontent.com/55627385/141142006-e316fb4c-3f9b-482a-9da1-6ea8e665ad9c.png)
Please fix it.

## Steps to Reproduce

* Open https://www.panda3d.org/
* Adjust the scale to 100% if it wasn't
* Scroll to the top of the official website

## Environment
 * Operating system: Windows11 Pro Insider Preview. Build 22471
 * Browser: Google Chrome

**Comment by hilbert-yaa** [comment]
> Do you have font scaling active in your OS?
Yes, I think the global scaling is set to 125% in windows settings.

> What is the internal width in pixels of your browser window?
From the query result in console, it's 958 × 571 on the 1920x1080 screen. This is the first time I encounter this problem on certain page, I'm not sure if this is the cause. You mean the problem might be some abnormal scaling settings on my OS?

**Comment by rdb** [comment]
Could you also try opening the site in Incognito Mode? Come to think of it, I wonder if you have some extensions that may be altering the layout of the Panda3D site.

I also use 125% scaling setting in Windows without issue.

**Comment by hilbert-yaa** [comment]
I've tried incognito mode, still get strange scaling. If this is not a general issue and won't cause problem then it's okay:)
