### ISSUE TITLE
A dark theme leads to an endless loading of the forum.

### ISSUE THREAD

**Issue by serkkz** [panda3d/www.panda3d.org#25]
It looks like the dark theme on the forum has broken, I see the logo of the endless content download, if I log out of the profile, a light theme is displayed, but the problem is that a dark theme is installed in my account. If I log in to the account, then the situation repeats.

**Comment by serkkz** [comment]
The problem was fixed on its own, which was not clear.

**Comment by rdb** [comment]
It wasn't fixed on its own, I fixed it last night. It was an incompatibility between some custom JavaScript in the theme and the new version of Discourse.
